### PR TITLE
Rename dbqueries

### PR DESCRIPTION
**Pull request by antoniotrkdz**

### CODE REVIEW

**Comment by des-des** [comment]
@antoniotrkdz this has commits on another pull on it, wait until I merge that one, then merge master into this branch and re-assign to me!

**Comment by des-des** [comment]
@majakudlicka @antoniotrkdz I am still waiting for you to merge master into this branch

image

image

I have already reviewed some of the commits on this pull..

**Comment by antoniotrkdz** [comment]
sorry, I didn't see it...my bad...I will do ASAP

**Comment by antoniotrkdz** [comment]
merged master in.

**Pull request merged**
